In [ ]:
!pip install -U nbformat

Requirement already satisfied: nbformat in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nbformat) (2.21.1)
Requirement already satisfied: jsonschema>=2.6 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nbformat) (4.23.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nbformat) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jsonschema>=2.6->nbformat) (25.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jsonschema>=2.6->nbformat) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jsonschema>=2.6->nbformat) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jsonschema>=2.6->nbformat) (0.23.1)
Requirement already satisfied: platformdirs>=2.5 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.6)
Requirement already satisfied: pywin32>=300 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (308)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.12.2)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\ryanc\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [ ]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\ryanc\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [ ]:
pip install plotly

Requirement already satisfied: plotly in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (6.0.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from plotly) (1.25.0)
Requirement already satisfied: packaging in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from plotly) (24.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\ryanc\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [ ]:
!pip install requests

Requirement already satisfied: requests in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (2025.1.31)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\ryanc\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\ryanc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\ryanc\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
import requests
pd.set_option('display.max_columns', None)
import time
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import nbformat

data = pd.read_excel('nba_player_data.xlsx')

In [ ]:
test_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2014-15&SeasonType=Regular%20Season&StatCategory=PTS'

In [ ]:
r = requests.get(url = test_url).json()

In [ ]:
r

{'resource': 'leagueleaders',
 'parameters': {'LeagueID': '00',
  'PerMode': 'Totals',
  'StatCategory': 'PTS',
  'Season': '2014-15',
  'SeasonType': 'Regular Season',
  'Scope': 'S',
  'ActiveFlag': None},
 'resultSet': {'name': 'LeagueLeaders',
  'headers': ['PLAYER_ID',
   'RANK',
   'PLAYER',
   'TEAM_ID',
   'TEAM',
   'GP',
   'MIN',
   'FGM',
   'FGA',
   'FG_PCT',
   'FG3M',
   'FG3A',
   'FG3_PCT',
   'FTM',
   'FTA',
   'FT_PCT',
   'OREB',
   'DREB',
   'REB',
   'AST',
   'STL',
   'BLK',
   'TOV',
   'PF',
   'PTS',
   'EFF',
   'AST_TOV',
   'STL_TOV'],
  'rowSet': [[201935,
    1,
    'James Harden',
    1610612745,
    'HOU',
    81,
    2981,
    647,
    1470,
    0.44,
    208,
    555,
    0.375,
    715,
    824,
    0.868,
    75,
    384,
    459,
    565,
    154,
    60,
    321,
    208,
    2217,
    2202,
    1.76,
    0.48],
   [201939,
    2,
    'Stephen Curry',
    1610612744,
    'GSW',
    80,
    2613,
    653,
    1341,
    0.487,
    286,
    646,
    0.443,
    308,
    337,
    0.914,
    56,
    285,
    341,
    619,
    163,
    16,
    249,
    158,
    1900,
    2073,
    2.49,
    0.66],
   [201566,
    3,
    'Russell Westbrook',
    1610612760,
    'OKC',
    67,
    2302,
    627,
    1471,
    0.426,
    86,
    288,
    0.299,
    546,
    654,
    0.835,
    124,
    364,
    488,
    574,
    140,
    14,
    293,
    184,
    1886,
    1857,
    1.96,
    0.48],
   [2544,
    4,
    'LeBron James',
    1610612739,
    'CLE',
    69,
    2493,
    624,
    1279,
    0.488,
    120,
    339,
    0.354,
    375,
    528,
    0.71,
    51,
    365,
    416,
    511,
    109,
    49,
    272,
    135,
    1743,
    1748,
    1.88,
    0.4],
   [203081,
    5,
    'Damian Lillard',
    1610612757,
    'POR',
    82,
    2925,
    590,
    1360,
    0.434,
    196,
    572,
    0.343,
    344,
    398,
    0.864,
    49,
    329,
    378,
    507,
    97,
    21,
    222,
    164,
    1720,
    1677,
    2.28,
    0.44],
   [202691,
    6,
    'Klay Thompson',
    1610612744,
    'GSW',
    77,
    2455,
    602,
    1299,
    0.463,
    239,
    545,
    0.439,
    225,
    256,
    0.879,
    27,
    220,
    247,
    222,
    87,
    60,
    149,
    122,
    1668,
    1407,
    1.49,
    0.58],
   [200746,
    7,
    'LaMarcus Aldridge',
    1610612757,
    'POR',
    71,
    2512,
    659,
    1415,
    0.466,
    37,
    105,
    0.352,
    306,
    362,
    0.845,
    177,
    549,
    726,
    124,
    48,
    68,
    122,
    125,
    1661,
    1693,
    1.02,
    0.39],
   [203076,
    8,
    'Anthony Davis',
    1610612740,
    'NOP',
    68,
    2455,
    642,
    1199,
    0.535,
    1,
    12,
    0.083,
    371,
    461,
    0.805,
    173,
    523,
    696,
    149,
    100,
    200,
    95,
    141,
    1656,
    2059,
    1.57,
    1.05],
   [202681,
    9,
    'Kyrie Irving',
    1610612739,
    'CLE',
    75,
    2730,
    578,
    1235,
    0.468,
    157,
    378,
    0.415,
    315,
    365,
    0.863,
    55,
    182,
    237,
    389,
    114,
    20,
    186,
    146,
    1628,
    1495,
    2.09,
    0.61],
   [101108,
    10,
    'Chris Paul',
    1610612746,
    'LAC',
    82,
    2857,
    568,
    1170,
    0.485,
    139,
    349,
    0.398,
    289,
    321,
    0.9,
    52,
    324,
    376,
    838,
    156,
    15,
    190,
    203,
    1564,
    2125,
    4.41,
    0.82],
   [101145,
    11,
    'Monta Ellis',
    1610612742,
    'DAL',
    80,
    2699,
    602,
    1354,
    0.445,
    81,
    284,
    0.285,
    228,
    303,
    0.752,
    34,
    156,
    190,
    329,
    148,
    25,
    198,
    197,
    1513,
    1180,
    1.66,
    0.75],
   [201933,
    12,
    'Blake Griffin',
    1610612746,
    'LAC',
    67,
    2356,
    574,
    1144,
    0.502,
    10,
    25,
    0.4,
    311,
    427,
    0.728,
    126,
    382,
    508,
    354,
    63,
    35,
    152,
    196,
    1469,
    1591,
    2.33,
    0.41],
   [202330,
    13,
    'Gordon Hayward',
    1610612762,
    'UTA',
    76,
    2618,
    484,
    1087,
    0.445,
    120,
    330,
    0.364,
    375,
    462,
    0.812,
    54,
    319,
    373,
    313,
    108,
    30,
    206,
    131,
    1463,
    1391,
    1.52,
    0.52],
   [2200,
    14,
    'Pau Gasol',
    1610612741,
    'CHI',
    78,
    2681,
    570,
    1153,
    0.494,
    12,
    26,
    0.462,
    294,
    366,
    0.803,
    220,
    699,
    919,
    210,
    25,
    147,
    158,
    147,
    1446,
    1934,
    1.33,
    0.16],
   [200752,
    15,
    'Rudy Gay',
    1610612758,
    'SAC',
    68,
    2408,
    508,
    1116,
    0.455,
    79,
    220,
    0.359,
    337,
    393,
    0.858,
    98,
    301,
    399,
    250,
    71,
    41,
    183,
    157,
    1432,
    1346,
    1.37,
    0.39],
   [202696,
    16,
    'Nikola Vučević',
    1610612753,
    'ORL',
    74,
    2529,
    631,
    1206,
    0.523,
    2,
    6,
    0.333,
    164,
    218,
    0.752,
    238,
    572,
    810,
    147,
    54,
    54,
    148,
    220,
    1428,
    1716,
    0.99,
    0.36],
   [202326,
    17,
    'DeMarcus Cousins',
    1610612758,
    'SAC',
    59,
    2013,
    498,
    1066,
    0.467,
    2,
    8,
    0.25,
    423,
    541,
    0.782,
    185,
    562,
    747,
    210,
    90,
    103,
    254,
    241,
    1421,
    1631,
    0.83,
    0.35],
   [201188,
    18,
    'Marc Gasol',
    1610612763,
    'MEM',
    81,
    2687,
    530,
    1072,
    0.494,
    3,
    17,
    0.176,
    350,
    440,
    0.795,
    115,
    515,
    630,
    307,
    70,
    131,
    176,
    208,
    1413,
    1743,
    1.74,
    0.4],
   [203952,
    19,
    'Andrew Wiggins',
    1610612750,
    'MIN',
    82,
    2969,
    497,
    1137,
    0.437,
    39,
    126,
    0.31,
    354,
    466,
    0.76,
    134,
    240,
    374,
    170,
    86,
    50,
    177,
    190,
    1387,
    1138,
    0.96,
    0.49],
   [202322,
    19,
    'John Wall',
    1610612764,
    'WAS',
    79,
    2837,
    519,
    1166,
    0.445,
    65,
    217,
    0.3,
    284,
    362,
    0.785,
    36,
    330,
    366,
    792,
    138,
    45,
    304,
    180,
    1387,
    1699,
    2.6,
    0.45],
   [202339,
    21,
    'Eric Bledsoe',
    1610612756,
    'PHX',
    81,
    2800,
    468,
    1046,
    0.447,
    88,
    272,
    0.324,
    353,
    441,
    0.8,
    72,
    351,
    423,
    493,
    127,
    45,
    274,
    189,
    1377,
    1525,
    1.8,
    0.46],
   [1717,
    22,
    'Dirk Nowitzki',
    1610612742,
    'DAL',
    77,
    2282,
    487,
    1062,
    0.459,
    104,
    274,
    0.38,
    255,
    289,
    0.882,
    44,
    413,
    457,
    143,
    39,
    33,
    82,
    160,
    1333,
    1314,
    1.74,
    0.48],
   [2548,
    23,
    'Dwyane Wade',
    1610612748,
    'MIA',
    62,
    1971,
    509,
    1084,
    0.47,
    29,
    102,
    0.284,
    284,
    370,
    0.768,
    58,
    161,
    219,
    299,
    73,
    21,
    209,
    105,
    1331,
    1073,
    1.43,
    0.35],
   [201936,
    24,
    'Tyreke Evans',
    1610612740,
    'NOP',
    79,
    2690,
    521,
    1165,
    0.447,
    69,
    227,
    0.304,
    202,
    291,
    0.694,
    82,
    334,
    416,
    521,
    100,
    37,
    246,
    198,
    1313,
    1408,
    2.12,
    0.41],
   [202710,
    25,
    'Jimmy Butler III',
    1610612741,
    'CHI',
    65,
    2513,
    421,
    912,
    0.462,
    73,
    193,
    0.378,
    386,
    463,
    0.834,
    114,
    265,
    379,
    212,
    114,
    36,
    93,
    108,
    1301,
    1381,
    2.28,
    1.23],
   [203506,
    26,
    'Victor Oladipo',
    1610612753,
    'ORL',
    72,
    2573,
    473,
    1086,
    0.436,
    84,
    248,
    0.339,
    262,
    320,
    0.819,
    51,
    251,
    302,
    295,
    120,
    19,
    204,
    187,
    1292,
    1153,
    1.45,
    0.59],
   [200755,
    27,
    'JJ Redick',
    1610612746,
    'LAC',
    78,
    2409,
    447,
    938,
    0.477,
    200,
    458,
    0.437,
    183,
    203,
    0.901,
    22,
    145,
    167,
    137,
    39,
    8,
    95,
    134,
    1277,
    1022,
    1.44,
    0.41],
   [201609,
    28,
    'Goran Dragic',
    1610612748,
    'MIA',
    78,
    2640,
    502,
    1002,
    0.501,
    90,
    259,
    0.347,
    181,
    234,
    0.774,
    81,
    193,
    274,
    350,
    78,
    15,
    173,
    195,
    1275,
    1266,
    2.02,
    0.45],
   [202693,
    29,
    'Markieff Morris',
    1610612756,
    'PHX',
    82,
    2581,
    512,
    1100,
    0.465,
    57,
    179,
    0.318,
    177,
    232,
    0.763,
    110,
    396,
    506,
    192,
    101,
    39,
    170,
    245,
    1258,
    1283,
    1.13,
    0.59],
   [200768,
    30,
    'Kyle Lowry',
    1610612761,
    'TOR',
    70,
    2414,
    430,
    1043,
    0.412,
    132,
    391,
    0.338,
    252,
    312,
    0.808,
    54,
    274,
    328,
    473,
    109,
    13,
    173,
    212,
    1244,
    1321,
    2.73,
    0.63],
   [101150,
    31,
    'Lou Williams',
    1610612761,
    'TOR',
    80,
    2016,
    375,
    928,
    0.404,
    152,
    447,
    0.34,
    340,
    395,
    0.861,
    24,
    127,
    151,
    164,
    88,
    10,
    101,
    103,
    1242,
    946,
    1.62,
    0.87],
   [201572,
    32,
    'Brook Lopez',
    1610612751,
    'BKN',
    72,
    2100,
    506,
    987,
    0.513,
    1,
    10,
    0.1,
    223,
    274,
    0.814,
    214,
    321,
    535,
    50,
    43,
    126,
    104,
    206,
    1236,
    1354,
    0.48,
    0.41],
   [201567,
    33,
    'Kevin Love',
    1610612739,
    'CLE',
    75,
    2532,
    413,
    952,
    0.434,
    144,
    392,
    0.367,
    258,
    321,
    0.804,
    142,
    589,
    731,
    168,
    51,
    39,
    122,
    140,
    1228,
    1493,
    1.38,
    0.42],
   [200794,
    34,
    'Paul Millsap',
    1610612737,
    'ATL',
    73,
    2390,
    443,
    930,
    0.476,
    77,
    216,
    0.356,
    255,
    337,
    0.757,
    139,
    431,
    570,
    223,
    130,
    69,
    166,
    201,
    1218,
    1475,
    1.34,
    0.78],
   [201942,
    35,
    'DeMar DeRozan',
    1610612761,
    'TOR',
    60,
    2100,
    409,
    990,
    0.413,
    25,
    88,
    0.284,
    361,
    434,
    0.832,
    41,
    236,
    277,
    210,
    73,
    11,
    137,
    122,
    1204,
    984,
    1.53,
    0.53],
   [202324,
    36,
    'Derrick Favors',
    1610612762,
    'UTA',
    74,
    2280,
    482,
    918,
    0.525,
    1,
    6,
    0.167,
    222,
    332,
    0.669,
    196,
    411,
    607,
    112,
    60,
    123,
    121,
    210,
    1187,
    1422,
    0.93,
    0.5],
   [201145,
    37,
    'Jeff Green',
    1610612763,
    'MEM',
    78,
    2455,
    416,
    967,
    0.43,
    97,
    292,
    0.332,
    239,
    287,
    0.833,
    64,
    264,
    328,
    134,
    53,
    34,
    108,
    147,
    1168,
    1010,
    1.24,
    0.49],
   [202699,
    38,
    'Tobias Harris',
    1610612753,
    'ORL',
    68,
    2369,
    442,
    949,
    0.466,
    87,
    239,
    0.364,
    193,
    245,
    0.788,
    73,
    357,
    430,
    124,
    69,
    36,
    115,
    134,
    1164,
    1149,
    1.08,
    0.6],
   [202683,
    39,
    'Enes Freedom',
    1610612760,
    'OKC',
    75,
    2136,
    482,
    928,
    0.519,
    16,
    45,
    0.356,
    183,
    234,
    0.782,
    277,
    394,
    671,
    55,
    36,
    29,
    145,
    189,
    1163,
    1312,
    0.38,
    0.25],
   [201952,
    40,
    'Jeff Teague',
    1610612737,
    'ATL',
    73,
    2228,
    408,
    887,
    0.46,
    71,
    207,
    0.343,
    275,
    319,
    0.862,
    30,
    154,
    184,
    513,
    125,
    31,
    205,
    139,
    1162,
    1287,
    2.5,
    0.61],
   [201143,
    41,
    'Al Horford',
    1610612737,
    'ATL',
    76,
    2318,
    519,
    965,
    0.538,
    11,
    36,
    0.306,
    107,
    141,
    0.759,
    131,
    413,
    544,
    244,
    68,
    98,
    100,
    121,
    1156,
    1530,
    2.44,
    0.68],
   [2207,
    42,
    'Joe Johnson',
    1610612751,
    'BKN',
    80,
    2791,
    446,
    1025,
    0.435,
    121,
    337,
    0.359,
    141,
    176,
    0.801,
    53,
    331,
    384,
    292,
    59,
    14,
    137,
    120,
    1154,
    1152,
    2.13,
    0.43],
   [201951,
    43,
    'Ty Lawson',
    1610612743,
    'DEN',
    75,
    2665,
    404,
    926,
    0.436,
    70,
    205,
    0.341,
    265,
    363,
    0.73,
    42,
    192,
    234,
    720,
    92,
    9,
    185,
    128,
    1143,
    1393,
    3.89,
    0.5],
   [2216,
    43,
    'Zach Randolph',
    1610612763,
    'MEM',
    71,
    2304,
    454,
    932,
    0.487,
    7,
    20,
    0.35,
    228,
    298,
    0.765,
    225,
    522,
    747,
    153,
    69,
    14,
    156,
    175,
    1143,
    1422,
    0.98,
    0.44],
   [203083,
    45,
    'Andre Drummond',
    1610612765,
    'DET',
    82,
    2502,
    494,
    961,
    0.514,
    0,
    2,
    0.0,
    142,
    365,
    0.389,
    437,
    667,
    1104,
    55,
    73,
    153,
    120,
    285,
    1130,
    1705,
    0.46,
    0.61],
   [202704,
    46,
    'Reggie Jackson',
    1610612765,
    'DET',
    77,
    2268,
    432,
    996,
    0.434,
    72,
    241,
    0.299,
    181,
    218,
    0.83,
    56,
    271,
    327,
    462,
    62,
    9,
    186,
    167,
    1117,
    1190,
    2.48,
    0.33],
   [201144,
    47,
    'Mike Conley',
    1610612763,
    'MEM',
    70,
    2225,
    393,
    882,
    0.446,
    107,
    277,
    0.386,
    214,
    249,
    0.859,
    29,
    180,
    209,
    375,
    89,
    14,
    156,
    139,
    1107,
    1114,
    2.4,
    0.57],
   [202738,
    48,
    'Isaiah Thomas',
    1610612738,
    'BOS',
    67,
    1726,
    335,
    796,
    0.421,
    129,
    346,
    0.373,
    302,
    348,
    0.868,
    33,
    120,
    153,
    284,
    57,
    5,
    143,
    150,
    1101,
    950,
    1.99,
    0.4],
   [202328,
    49,
    'Greg Monroe',
    1610612765,
    'DET',
    69,
    2137,
    423,
    853,
    0.496,
    0,
    0,
    0.0,
    252,
    336,
    0.75,
    229,
    475,
    704,
    142,
    78,
    34,
    149,
    148,
    1098,
    1393,
    0.95,
    0.52],
   [201163,
    50,
    'Wilson Chandler',
    1610612743,
    'DEN',
    78,
    2471,
    418,
    975,
    0.429,
    139,
    406,
    0.342,
    110,
    142,
    0.775,
    96,
    379,
    475,
    134,
    58,
    29,
    110,
    231,
    1085,
    1082,
    1.22,
    0.53],
   [2744,
    51,
    'Al Jefferson',
    1610612766,
    'CHA',
    65,
    1992,
    486,
    1010,
    0.481,
    2,
    5,
    0.4,
    108,
    165,
    0.655,
    99,
    449,
    548,
    113,
    47,
    84,
    68,
    139,
    1082,
    1225,
    1.66,
    0.69],
   [202689,
    52,
    'Kemba Walker',
    1610612766,
    'CHA',
    62,
    2119,
    378,
    981,
    0.385,
    85,
    280,
    0.304,
    234,
    283,
    0.827,
    35,
    185,
    220,
    318,
    89,
    31,
    100,
    92,
    1075,
    981,
    3.18,
    0.89],
   [202340,
    53,
    'Avery Bradley',
    1610612738,
    'BOS',
    77,
    2428,
    434,
    1013,
    0.428,
    124,
    352,
    0.352,
    79,
    100,
    0.79,
    46,
    195,
    241,
    135,
    82,
    15,
    109,
    177,
    1071,
    835,
    1.24,
    0.75],
   [201152,
    53,
    'Thaddeus Young',
    1610612751,
    'BKN',
    76,
    2434,
    451,
    968,
    0.466,
    38,
    115,
    0.33,
    131,
    200,
    0.655,
    127,
    284,
    411,
    173,
    124,
    25,
    117,
    171,
    1071,
    1101,
    1.48,
    1.06],
   [202688,
    55,
    'Brandon Knight',
    1610612756,
    'PHX',
    63,
    2035,
    375,
    888,
    0.422,
    125,
    321,
    0.389,
    195,
    223,
    0.874,
    28,
    216,
    244,
    330,
    90,
    10,
    189,
    114,
    1070,
    1014,
    1.75,
    0.48],
   [1495,
    55,
    'Tim Duncan',
    1610612759,
    'SAS',
    77,
    2227,
    419,
    819,
    0.512,
    2,
    7,
    0.286,
    230,
    311,
    0.74,
    170,
    534,
    704,
    230,
    63,
    151,
    131,
    165,
    1070,
    1606,
    1.76,
    0.48],
   [202695,
    57,
    'Kawhi Leonard',
    1610612759,
    'SAS',
    64,
    2033,
    394,
    822,
    0.479,
    67,
    192,
    0.349,
    202,
    252,
    0.802,
    85,
    376,
    461,
    161,
    148,
    48,
    97,
    128,
    1057,
    1300,
    1.66,
    1.53],
   [203114,
    58,
    'Khris Middleton',
    1610612749,
    'MIL',
    79,
    2378,
    406,
    869,
    0.467,
    109,
    268,
    0.407,
    134,
    156,
    0.859,
    48,
    299,
    347,
    182,
    122,
    11,
    113,
    183,
    1055,
    1119,
    1.61,
    1.08],
   [2772,
    59,
    'Trevor Ariza',
    1610612745,
    'HOU',
    82,
    2930,
    366,
    910,
    0.402,
    194,
    555,
    0.35,
    122,
    143,
    0.853,
    77,
    382,
    459,
    209,
    152,
    17,
    141,
    186,
    1048,
    1179,
    1.48,
    1.08],
   [203484,
    60,
    'Kentavious Caldwell-Pope',
    1610612765,
    'DET',
    82,
    2587,
    390,
    972,
    0.401,
    153,
    444,
    0.345,
    110,
    158,
    0.696,
    46,
    209,
    255,
    109,
    93,
    18,
    94,
    161,
    1043,
    794,
    1.16,
    0.99],
   [202718,
    61,
    'Chandler Parsons',
    1610612742,
    'DAL',
    66,
    2186,
    383,
    829,
    0.462,
    132,
    347,
    0.38,
    139,
    193,
    0.72,
    64,
    259,
    323,
    161,
    69,
    19,
    96,
    140,
    1037,
    1013,
    1.68,
    0.72],
   [201167,
    62,
    'Arron Afflalo',
    1610612757,
    'POR',
    78,
    2502,
    375,
    884,
    0.424,
    118,
    333,
    0.354,
    167,
    198,
    0.843,
    27,
    220,
    247,
    129,
    41,
    7,
    116,
    167,
    1035,
    803,
    1.11,
    0.35],
   [203507,
    63,
    'Giannis Antetokounmpo',
    1610612749,
    'MIL',
    81,
    2541,
    383,
    780,
    0.491,
    7,
    44,
    0.159,
    257,
    347,
    0.741,
    100,
    442,
    542,
    207,
    73,
    85,
    173,
    254,
    1030,
    1277,
    1.2,
    0.42],
   [2746,
    64,
    'Josh Smith',
    1610612745,
    'HOU',
    83,
    2301,
    414,
    987,
    0.419,
    72,
    228,
    0.316,
    127,
    255,
    0.498,
    152,
    378,
    530,
    277,
    87,
    116,
    206,
    228,
    1027,
    1130,
    1.34,
    0.42],
   [2037,
    65,
    'Jamal Crawford',
    1610612746,
    'LAC',
    64,
    1703,
    332,
    839,
    0.396,
    119,
    364,
    0.327,
    227,
    252,
    0.901,
    18,
    106,
    124,
    158,
    59,
    14,
    92,
    108,
    1010,
    741,
    1.72,
    0.64],
   [2736,
    66,
    'Luol Deng',
    1610612748,
    'MIA',
    72,
    2421,
    369,
    787,
    0.469,
    78,
    220,
    0.355,
    191,
    251,
    0.761,
    103,
    273,
    376,
    139,
    65,
    22,
    108,
    109,
    1007,
    1023,
    1.29,
    0.6],
   [101162,
    67,
    'Marcin Gortat',
    1610612764,
    'WAS',
    82,
    2453,
    439,
    775,
    0.566,
    0,
    3,
    0.0,
    123,
    175,
    0.703,
    180,
    537,
    717,
    97,
    49,
    110,
    100,
    191,
    1001,
    1486,
    0.97,
    0.49],
   [203463,
    68,
    'Ben McLemore',
    1610612758,
    'SAC',
    82,
    2670,
    363,
    831,
    0.437,
    140,
    391,
    0.358,
    130,
    160,
    0.813,
    31,
    210,
    241,
    140,
    77,
    19,
    138,
    219,
    996,
    837,
    1.01,
    0.56],
   [2225,
    69,
    'Tony Parker',
    1610612759,
    'SAS',
    68,
    1953,
    404,
    832,
    0.486,
    38,
    89,
    0.427,
    130,
    166,
    0.783,
    15,
    114,
    129,
    335,
    44,
    2,
    146,
    108,
    976,
    876,
    2.29,
    0.3],
   [203504,
    70,

In [ ]:
table_headers = r['resultSet']['headers']

In [ ]:
r['resultSet']['rowSet']

[[201935,
  1,
  'James Harden',
  1610612745,
  'HOU',
  81,
  2981,
  647,
  1470,
  0.44,
  208,
  555,
  0.375,
  715,
  824,
  0.868,
  75,
  384,
  459,
  565,
  154,
  60,
  321,
  208,
  2217,
  2202,
  1.76,
  0.48],
 [201939,
  2,
  'Stephen Curry',
  1610612744,
  'GSW',
  80,
  2613,
  653,
  1341,
  0.487,
  286,
  646,
  0.443,
  308,
  337,
  0.914,
  56,
  285,
  341,
  619,
  163,
  16,
  249,
  158,
  1900,
  2073,
  2.49,
  0.66],
 [201566,
  3,
  'Russell Westbrook',
  1610612760,
  'OKC',
  67,
  2302,
  627,
  1471,
  0.426,
  86,
  288,
  0.299,
  546,
  654,
  0.835,
  124,
  364,
  488,
  574,
  140,
  14,
  293,
  184,
  1886,
  1857,
  1.96,
  0.48],
 [2544,
  4,
  'LeBron James',
  1610612739,
  'CLE',
  69,
  2493,
  624,
  1279,
  0.488,
  120,
  339,
  0.354,
  375,
  528,
  0.71,
  51,
  365,
  416,
  511,
  109,
  49,
  272,
  135,
  1743,
  1748,
  1.88,
  0.4],
 [203081,
  5,
  'Damian Lillard',
  1610612757,
  'POR',
  82,
  2925,
  590,
  1360,
  0.434,
  196,
  572,
  0.343,
  344,
  398,
  0.864,
  49,
  329,
  378,
  507,
  97,
  21,
  222,
  164,
  1720,
  1677,
  2.28,
  0.44],
 [202691,
  6,
  'Klay Thompson',
  1610612744,
  'GSW',
  77,
  2455,
  602,
  1299,
  0.463,
  239,
  545,
  0.439,
  225,
  256,
  0.879,
  27,
  220,
  247,
  222,
  87,
  60,
  149,
  122,
  1668,
  1407,
  1.49,
  0.58],
 [200746,
  7,
  'LaMarcus Aldridge',
  1610612757,
  'POR',
  71,
  2512,
  659,
  1415,
  0.466,
  37,
  105,
  0.352,
  306,
  362,
  0.845,
  177,
  549,
  726,
  124,
  48,
  68,
  122,
  125,
  1661,
  1693,
  1.02,
  0.39],
 [203076,
  8,
  'Anthony Davis',
  1610612740,
  'NOP',
  68,
  2455,
  642,
  1199,
  0.535,
  1,
  12,
  0.083,
  371,
  461,
  0.805,
  173,
  523,
  696,
  149,
  100,
  200,
  95,
  141,
  1656,
  2059,
  1.57,
  1.05],
 [202681,
  9,
  'Kyrie Irving',
  1610612739,
  'CLE',
  75,
  2730,
  578,
  1235,
  0.468,
  157,
  378,
  0.415,
  315,
  365,
  0.863,
  55,
  182,
  237,
  389,
  114,
  20,
  186,
  146,
  1628,
  1495,
  2.09,
  0.61],
 [101108,
  10,
  'Chris Paul',
  1610612746,
  'LAC',
  82,
  2857,
  568,
  1170,
  0.485,
  139,
  349,
  0.398,
  289,
  321,
  0.9,
  52,
  324,
  376,
  838,
  156,
  15,
  190,
  203,
  1564,
  2125,
  4.41,
  0.82],
 [101145,
  11,
  'Monta Ellis',
  1610612742,
  'DAL',
  80,
  2699,
  602,
  1354,
  0.445,
  81,
  284,
  0.285,
  228,
  303,
  0.752,
  34,
  156,
  190,
  329,
  148,
  25,
  198,
  197,
  1513,
  1180,
  1.66,
  0.75],
 [201933,
  12,
  'Blake Griffin',
  1610612746,
  'LAC',
  67,
  2356,
  574,
  1144,
  0.502,
  10,
  25,
  0.4,
  311,
  427,
  0.728,
  126,
  382,
  508,
  354,
  63,
  35,
  152,
  196,
  1469,
  1591,
  2.33,
  0.41],
 [202330,
  13,
  'Gordon Hayward',
  1610612762,
  'UTA',
  76,
  2618,
  484,
  1087,
  0.445,
  120,
  330,
  0.364,
  375,
  462,
  0.812,
  54,
  319,
  373,
  313,
  108,
  30,
  206,
  131,
  1463,
  1391,
  1.52,
  0.52],
 [2200,
  14,
  'Pau Gasol',
  1610612741,
  'CHI',
  78,
  2681,
  570,
  1153,
  0.494,
  12,
  26,
  0.462,
  294,
  366,
  0.803,
  220,
  699,
  919,
  210,
  25,
  147,
  158,
  147,
  1446,
  1934,
  1.33,
  0.16],
 [200752,
  15,
  'Rudy Gay',
  1610612758,
  'SAC',
  68,
  2408,
  508,
  1116,
  0.455,
  79,
  220,
  0.359,
  337,
  393,
  0.858,
  98,
  301,
  399,
  250,
  71,
  41,
  183,
  157,
  1432,
  1346,
  1.37,
  0.39],
 [202696,
  16,
  'Nikola Vučević',
  1610612753,
  'ORL',
  74,
  2529,
  631,
  1206,
  0.523,
  2,
  6,
  0.333,
  164,
  218,
  0.752,
  238,
  572,
  810,
  147,
  54,
  54,
  148,
  220,
  1428,
  1716,
  0.99,
  0.36],
 [202326,
  17,
  'DeMarcus Cousins',
  1610612758,
  'SAC',
  59,
  2013,
  498,
  1066,
  0.467,
  2,
  8,
  0.25,
  423,
  541,
  0.782,
  185,
  562,
  747,
  210,
  90,
  103,
  254,
  241,
  1421,
  1631,
  0.83,
  0.35],
 [201188,
  18,
  'Marc Gasol',
  1610612763,
  'MEM',
  81,
  2687,
  530,
  1072,
  0.494,
  3,
  17,
  0.176,
  350,
  440,
  0.795,
  115,
  515,
  630,
  307,
  70,
  131,
  176,
  208,
  1413,
  1743,
  1.74,
  0.4],
 [203952,
  19,
  'Andrew Wiggins',
  1610612750,
  'MIN',
  82,
  2969,
  497,
  1137,
  0.437,
  39,
  126,
  0.31,
  354,
  466,
  0.76,
  134,
  240,
  374,
  170,
  86,
  50,
  177,
  190,
  1387,
  1138,
  0.96,
  0.49],
 [202322,
  19,
  'John Wall',
  1610612764,
  'WAS',
  79,
  2837,
  519,
  1166,
  0.445,
  65,
  217,
  0.3,
  284,
  362,
  0.785,
  36,
  330,
  366,
  792,
  138,
  45,
  304,
  180,
  1387,
  1699,
  2.6,
  0.45],
 [202339,
  21,
  'Eric Bledsoe',
  1610612756,
  'PHX',
  81,
  2800,
  468,
  1046,
  0.447,
  88,
  272,
  0.324,
  353,
  441,
  0.8,
  72,
  351,
  423,
  493,
  127,
  45,
  274,
  189,
  1377,
  1525,
  1.8,
  0.46],
 [1717,
  22,
  'Dirk Nowitzki',
  1610612742,
  'DAL',
  77,
  2282,
  487,
  1062,
  0.459,
  104,
  274,
  0.38,
  255,
  289,
  0.882,
  44,
  413,
  457,
  143,
  39,
  33,
  82,
  160,
  1333,
  1314,
  1.74,
  0.48],
 [2548,
  23,
  'Dwyane Wade',
  1610612748,
  'MIA',
  62,
  1971,
  509,
  1084,
  0.47,
  29,
  102,
  0.284,
  284,
  370,
  0.768,
  58,
  161,
  219,
  299,
  73,
  21,
  209,
  105,
  1331,
  1073,
  1.43,
  0.35],
 [201936,
  24,
  'Tyreke Evans',
  1610612740,
  'NOP',
  79,
  2690,
  521,
  1165,
  0.447,
  69,
  227,
  0.304,
  202,
  291,
  0.694,
  82,
  334,
  416,
  521,
  100,
  37,
  246,
  198,
  1313,
  1408,
  2.12,
  0.41],
 [202710,
  25,
  'Jimmy Butler III',
  1610612741,
  'CHI',
  65,
  2513,
  421,
  912,
  0.462,
  73,
  193,
  0.378,
  386,
  463,
  0.834,
  114,
  265,
  379,
  212,
  114,
  36,
  93,
  108,
  1301,
  1381,
  2.28,
  1.23],
 [203506,
  26,
  'Victor Oladipo',
  1610612753,
  'ORL',
  72,
  2573,
  473,
  1086,
  0.436,
  84,
  248,
  0.339,
  262,
  320,
  0.819,
  51,
  251,
  302,
  295,
  120,
  19,
  204,
  187,
  1292,
  1153,
  1.45,
  0.59],
 [200755,
  27,
  'JJ Redick',
  1610612746,
  'LAC',
  78,
  2409,
  447,
  938,
  0.477,
  200,
  458,
  0.437,
  183,
  203,
  0.901,
  22,
  145,
  167,
  137,
  39,
  8,
  95,
  134,
  1277,
  1022,
  1.44,
  0.41],
 [201609,
  28,
  'Goran Dragic',
  1610612748,
  'MIA',
  78,
  2640,
  502,
  1002,
  0.501,
  90,
  259,
  0.347,
  181,
  234,
  0.774,
  81,
  193,
  274,
  350,
  78,
  15,
  173,
  195,
  1275,
  1266,
  2.02,
  0.45],
 [202693,
  29,
  'Markieff Morris',
  1610612756,
  'PHX',
  82,
  2581,
  512,
  1100,
  0.465,
  57,
  179,
  0.318,
  177,
  232,
  0.763,
  110,
  396,
  506,
  192,
  101,
  39,
  170,
  245,
  1258,
  1283,
  1.13,
  0.59],
 [200768,
  30,
  'Kyle Lowry',
  1610612761,
  'TOR',
  70,
  2414,
  430,
  1043,
  0.412,
  132,
  391,
  0.338,
  252,
  312,
  0.808,
  54,
  274,
  328,
  473,
  109,
  13,
  173,
  212,
  1244,
  1321,
  2.73,
  0.63],
 [101150,
  31,
  'Lou Williams',
  1610612761,
  'TOR',
  80,
  2016,
  375,
  928,
  0.404,
  152,
  447,
  0.34,
  340,
  395,
  0.861,
  24,
  127,
  151,
  164,
  88,
  10,
  101,
  103,
  1242,
  946,
  1.62,
  0.87],
 [201572,
  32,
  'Brook Lopez',
  1610612751,
  'BKN',
  72,
  2100,
  506,
  987,
  0.513,
  1,
  10,
  0.1,
  223,
  274,
  0.814,
  214,
  321,
  535,
  50,
  43,
  126,
  104,
  206,
  1236,
  1354,
  0.48,
  0.41],
 [201567,
  33,
  'Kevin Love',
  1610612739,
  'CLE',
  75,
  2532,
  413,
  952,
  0.434,
  144,
  392,
  0.367,
  258,
  321,
  0.804,
  142,
  589,
  731,
  168,
  51,
  39,
  122,
  140,
  1228,
  1493,
  1.38,
  0.42],
 [200794,
  34,
  'Paul Millsap',
  1610612737,
  'ATL',
  73,
  2390,
  443,
  930,
  0.476,
  77,
  216,
  0.356,
  255,
  337,
  0.757,
  139,
  431,
  570,
  223,
  130,
  69,
  166,
  201,
  1218,
  1475,
  1.34,
  0.78],
 [201942,
  35,
  'DeMar DeRozan',
  1610612761,
  'TOR',
  60,
  2100,
  409,
  990,
  0.413,
  25,
  88,
  0.284,
  361,
  434,
  0.832,
  41,
  236,
  277,
  210,
  73,
  11,
  137,
  122,
  1204,
  984,
  1.53,
  0.53],
 [202324,
  36,
  'Derrick Favors',
  1610612762,
  'UTA',
  74,
  2280,
  482,
  918,
  0.525,
  1,
  6,
  0.167,
  222,
  332,
  0.669,
  196,
  411,
  607,
  112,
  60,
  123,
  121,
  210,
  1187,
  1422,
  0.93,
  0.5],
 [201145,
  37,
  'Jeff Green',
  1610612763,
  'MEM',
  78,
  2455,
  416,
  967,
  0.43,
  97,
  292,
  0.332,
  239,
  287,
  0.833,
  64,
  264,
  328,
  134,
  53,
  34,
  108,
  147,
  1168,
  1010,
  1.24,
  0.49],
 [202699,
  38,
  'Tobias Harris',
  1610612753,
  'ORL',
  68,
  2369,
  442,
  949,
  0.466,
  87,
  239,
  0.364,
  193,
  245,
  0.788,
  73,
  357,
  430,
  124,
  69,
  36,
  115,
  134,
  1164,
  1149,
  1.08,
  0.6],
 [202683,
  39,
  'Enes Freedom',
  1610612760,
  'OKC',
  75,
  2136,
  482,
  928,
  0.519,
  16,
  45,
  0.356,
  183,
  234,
  0.782,
  277,
  394,
  671,
  55,
  36,
  29,
  145,
  189,
  1163,
  1312,
  0.38,
  0.25],
 [201952,
  40,
  'Jeff Teague',
  1610612737,
  'ATL',
  73,
  2228,
  408,
  887,
  0.46,
  71,
  207,
  0.343,
  275,
  319,
  0.862,
  30,
  154,
  184,
  513,
  125,
  31,
  205,
  139,
  1162,
  1287,
  2.5,
  0.61],
 [201143,
  41,
  'Al Horford',
  1610612737,
  'ATL',
  76,
  2318,
  519,
  965,
  0.538,
  11,
  36,
  0.306,
  107,
  141,
  0.759,
  131,
  413,
  544,
  244,
  68,
  98,
  100,
  121,
  1156,
  1530,
  2.44,
  0.68],
 [2207,
  42,
  'Joe Johnson',
  1610612751,
  'BKN',
  80,
  2791,
  446,
  1025,
  0.435,
  121,
  337,
  0.359,
  141,
  176,
  0.801,
  53,
  331,
  384,
  292,
  59,
  14,
  137,
  120,
  1154,
  1152,
  2.13,
  0.43],
 [201951,
  43,
  'Ty Lawson',
  1610612743,
  'DEN',
  75,
  2665,
  404,
  926,
  0.436,
  70,
  205,
  0.341,
  265,
  363,
  0.73,
  42,
  192,
  234,
  720,
  92,
  9,
  185,
  128,
  1143,
  1393,
  3.89,
  0.5],
 [2216,
  43,
  'Zach Randolph',
  1610612763,
  'MEM',
  71,
  2304,
  454,
  932,
  0.487,
  7,
  20,
  0.35,
  228,
  298,
  0.765,
  225,
  522,
  747,
  153,
  69,
  14,
  156,
  175,
  1143,
  1422,
  0.98,
  0.44],
 [203083,
  45,
  'Andre Drummond',
  1610612765,
  'DET',
  82,
  2502,
  494,
  961,
  0.514,
  0,
  2,
  0.0,
  142,
  365,
  0.389,
  437,
  667,
  1104,
  55,
  73,
  153,
  120,
  285,
  1130,
  1705,
  0.46,
  0.61],
 [202704,
  46,
  'Reggie Jackson',
  1610612765,
  'DET',
  77,
  2268,
  432,
  996,
  0.434,
  72,
  241,
  0.299,
  181,
  218,
  0.83,
  56,
  271,
  327,
  462,
  62,
  9,
  186,
  167,
  1117,
  1190,
  2.48,
  0.33],
 [201144,
  47,
  'Mike Conley',
  1610612763,
  'MEM',
  70,
  2225,
  393,
  882,
  0.446,
  107,
  277,
  0.386,
  214,
  249,
  0.859,
  29,
  180,
  209,
  375,
  89,
  14,
  156,
  139,
  1107,
  1114,
  2.4,
  0.57],
 [202738,
  48,
  'Isaiah Thomas',
  1610612738,
  'BOS',
  67,
  1726,
  335,
  796,
  0.421,
  129,
  346,
  0.373,
  302,
  348,
  0.868,
  33,
  120,
  153,
  284,
  57,
  5,
  143,
  150,
  1101,
  950,
  1.99,
  0.4],
 [202328,
  49,
  'Greg Monroe',
  1610612765,
  'DET',
  69,
  2137,
  423,
  853,
  0.496,
  0,
  0,
  0.0,
  252,
  336,
  0.75,
  229,
  475,
  704,
  142,
  78,
  34,
  149,
  148,
  1098,
  1393,
  0.95,
  0.52],
 [201163,
  50,
  'Wilson Chandler',
  1610612743,
  'DEN',
  78,
  2471,
  418,
  975,
  0.429,
  139,
  406,
  0.342,
  110,
  142,
  0.775,
  96,
  379,
  475,
  134,
  58,
  29,
  110,
  231,
  1085,
  1082,
  1.22,
  0.53],
 [2744,
  51,
  'Al Jefferson',
  1610612766,
  'CHA',
  65,
  1992,
  486,
  1010,
  0.481,
  2,
  5,
  0.4,
  108,
  165,
  0.655,
  99,
  449,
  548,
  113,
  47,
  84,
  68,
  139,
  1082,
  1225,
  1.66,
  0.69],
 [202689,
  52,
  'Kemba Walker',
  1610612766,
  'CHA',
  62,
  2119,
  378,
  981,
  0.385,
  85,
  280,
  0.304,
  234,
  283,
  0.827,
  35,
  185,
  220,
  318,
  89,
  31,
  100,
  92,
  1075,
  981,
  3.18,
  0.89],
 [202340,
  53,
  'Avery Bradley',
  1610612738,
  'BOS',
  77,
  2428,
  434,
  1013,
  0.428,
  124,
  352,
  0.352,
  79,
  100,
  0.79,
  46,
  195,
  241,
  135,
  82,
  15,
  109,
  177,
  1071,
  835,
  1.24,
  0.75],
 [201152,
  53,
  'Thaddeus Young',
  1610612751,
  'BKN',
  76,
  2434,
  451,
  968,
  0.466,
  38,
  115,
  0.33,
  131,
  200,
  0.655,
  127,
  284,
  411,
  173,
  124,
  25,
  117,
  171,
  1071,
  1101,
  1.48,
  1.06],
 [202688,
  55,
  'Brandon Knight',
  1610612756,
  'PHX',
  63,
  2035,
  375,
  888,
  0.422,
  125,
  321,
  0.389,
  195,
  223,
  0.874,
  28,
  216,
  244,
  330,
  90,
  10,
  189,
  114,
  1070,
  1014,
  1.75,
  0.48],
 [1495,
  55,
  'Tim Duncan',
  1610612759,
  'SAS',
  77,
  2227,
  419,
  819,
  0.512,
  2,
  7,
  0.286,
  230,
  311,
  0.74,
  170,
  534,
  704,
  230,
  63,
  151,
  131,
  165,
  1070,
  1606,
  1.76,
  0.48],
 [202695,
  57,
  'Kawhi Leonard',
  1610612759,
  'SAS',
  64,
  2033,
  394,
  822,
  0.479,
  67,
  192,
  0.349,
  202,
  252,
  0.802,
  85,
  376,
  461,
  161,
  148,
  48,
  97,
  128,
  1057,
  1300,
  1.66,
  1.53],
 [203114,
  58,
  'Khris Middleton',
  1610612749,
  'MIL',
  79,
  2378,
  406,
  869,
  0.467,
  109,
  268,
  0.407,
  134,
  156,
  0.859,
  48,
  299,
  347,
  182,
  122,
  11,
  113,
  183,
  1055,
  1119,
  1.61,
  1.08],
 [2772,
  59,
  'Trevor Ariza',
  1610612745,
  'HOU',
  82,
  2930,
  366,
  910,
  0.402,
  194,
  555,
  0.35,
  122,
  143,
  0.853,
  77,
  382,
  459,
  209,
  152,
  17,
  141,
  186,
  1048,
  1179,
  1.48,
  1.08],
 [203484,
  60,
  'Kentavious Caldwell-Pope',
  1610612765,
  'DET',
  82,
  2587,
  390,
  972,
  0.401,
  153,
  444,
  0.345,
  110,
  158,
  0.696,
  46,
  209,
  255,
  109,
  93,
  18,
  94,
  161,
  1043,
  794,
  1.16,
  0.99],
 [202718,
  61,
  'Chandler Parsons',
  1610612742,
  'DAL',
  66,
  2186,
  383,
  829,
  0.462,
  132,
  347,
  0.38,
  139,
  193,
  0.72,
  64,
  259,
  323,
  161,
  69,
  19,
  96,
  140,
  1037,
  1013,
  1.68,
  0.72],
 [201167,
  62,
  'Arron Afflalo',
  1610612757,
  'POR',
  78,
  2502,
  375,
  884,
  0.424,
  118,
  333,
  0.354,
  167,
  198,
  0.843,
  27,
  220,
  247,
  129,
  41,
  7,
  116,
  167,
  1035,
  803,
  1.11,
  0.35],
 [203507,
  63,
  'Giannis Antetokounmpo',
  1610612749,
  'MIL',
  81,
  2541,
  383,
  780,
  0.491,
  7,
  44,
  0.159,
  257,
  347,
  0.741,
  100,
  442,
  542,
  207,
  73,
  85,
  173,
  254,
  1030,
  1277,
  1.2,
  0.42],
 [2746,
  64,
  'Josh Smith',
  1610612745,
  'HOU',
  83,
  2301,
  414,
  987,
  0.419,
  72,
  228,
  0.316,
  127,
  255,
  0.498,
  152,
  378,
  530,
  277,
  87,
  116,
  206,
  228,
  1027,
  1130,
  1.34,
  0.42],
 [2037,
  65,
  'Jamal Crawford',
  1610612746,
  'LAC',
  64,
  1703,
  332,
  839,
  0.396,
  119,
  364,
  0.327,
  227,
  252,
  0.901,
  18,
  106,
  124,
  158,
  59,
  14,
  92,
  108,
  1010,
  741,
  1.72,
  0.64],
 [2736,
  66,
  'Luol Deng',
  1610612748,
  'MIA',
  72,
  2421,
  369,
  787,
  0.469,
  78,
  220,
  0.355,
  191,
  251,
  0.761,
  103,
  273,
  376,
  139,
  65,
  22,
  108,
  109,
  1007,
  1023,
  1.29,
  0.6],
 [101162,
  67,
  'Marcin Gortat',
  1610612764,
  'WAS',
  82,
  2453,
  439,
  775,
  0.566,
  0,
  3,
  0.0,
  123,
  175,
  0.703,
  180,
  537,
  717,
  97,
  49,
  110,
  100,
  191,
  1001,
  1486,
  0.97,
  0.49],
 [203463,
  68,
  'Ben McLemore',
  1610612758,
  'SAC',
  82,
  2670,
  363,
  831,
  0.437,
  140,
  391,
  0.358,
  130,
  160,
  0.813,
  31,
  210,
  241,
  140,
  77,
  19,
  138,
  219,
  996,
  837,
  1.01,
  0.56],
 [2225,
  69,
  'Tony Parker',
  1610612759,
  'SAS',
  68,
  1953,
  404,
  832,
  0.486,
  38,
  89,
  0.427,
  130,
  166,
  0.783,
  15,
  114,
  129,
  335,
  44,
  2,
  146,
  108,
  976,
  876,
  2.29,
  0.3],
 [203504,
  70,
  'Trey Burke',
  1610612762,
  'UTA',
  76,
  2288,
  370,
  1005,
  0.368,
  124,
  390,
  0.318,
  109,
  145,
  0.752,
  31,
  173,
  204,
  328,
  65,
  15,
  124,
  119,
  973,
  790,
  2.65,
  0.52],
 [201945,
  71,
  'Gerald Henderson',
  1610612766,
  'CHA',
  80,
  2315,
  370,
  847,
  0.437,
  45,
  136,
  0.331,
  184,
  217,
  0.848,
  36,
  237,
  273,
  206,
  51,
  22,
  110,
  135,
  969,
  901,
  1.87,
  0.46],
 [2546,
  72,
  'Carmelo Anthony',
  1610612752,
  'NYK',
  40,
  1428,
  358,
  806,
  0.444,
  61,
  179,
  0.341,
  189,
  237,
  0.797,
  72,
  192,
  264,
  122,
  40,
  17,
  89,
  87,
  966,
  824,
  1.37,
  0.45],
 [203487,
  72,
  'Michael Carter-Williams',
  1610612749,
  'MIL',
  66,
  2150,
  364,
  919,
  0.396,
  36,
  153,
  0.235,
  202,
  291,
  0.694,
  64,
  289,
  353,
  442,
  111,
  30,
  253,
  167,
  966,
  1005,
  1.75,
  0.44],
 [2590,
  74,
  'Mo Williams',
  1610612766,
  'CHA',
  68,
  1980,
  341,
  860,
  0.397,
  119,
  348,
  0.342,
  163,
  187,
  0.872,
  22,
  152,
  174,
  424,
  46,
  14,
  172,
  162,
  964,
  907,
  2.46,
  0.27],
 [202685,
  75,
  'Jonas Valančiūnas',
  1610612761,
  'TOR',
  80,
  2096,
  373,
  652,
  0.572,
  0,
  1,
  0.0,
  217,
  276,
  0.786,
  215,
  478,
  693,
  39,
  33,
  95,
  109,
  222,
  963,
  1376,
  0.36,
  0.3],
 [203078,
  76,
  'Bradley Beal',
  1610612764,
  'WAS',
  63,
  2107,
  363,
  851,
  0.427,
  106,
  259,
  0.409,
  130,
  166,
  0.783,
  57,
  184,
  241,
  194,
  76,
  18,
  123,
  136,
  962,
  844,
  1.58,
  0.62],
 [101127,
  77,
  'Jarrett Jack',
  1610612751,
  'BKN',
  80,
  2241,
  359,
  817,
  0.439,
  39,
  146,
  0.267,
  200,
  227,
  0.881,
  19,
  226,
  245,
  373,
  75,
  13,
  191,
  143,
  957,
  987,
  1.95,
  0.39],
 [202083,
  78,
  'Wesley Matthews',
  1610612757,
  'POR',
  60,
  2024,
  337,
  752,
  0.448,
  173,
  445,
  0.389,
  109,
  145,
  0.752,
  38,
  184,
  222,
  139,
  77,
  10,
  81,
  132,
  956,
  872,
  1.72,
  0.95],
 [201166,
  79,
  'Aaron Brooks',
  1610612741,
  'CHI',
  82,
  1885,
  344,
  817,
  0.421,
  121,
  313,
  0.387,
  145,
  174,
  0.833,
  32,
  134,
  166,
  261,
  54,
  15,
  157,
  189,
  954,
  791,
  1.66,
  0.34],
 [201980,
  80,
  'Danny Green',
  1610612759,
  'SAS',
  81,
  2312,
  322,
  738,
  0.436,
  191,
  457,
  0.418,
  111,
  127,
  0.874,
  54,
  289,
  343,
  158,
  101,
  87,
  93,
  163,
  946,
  1110,
  1.7,
  1.09],
 [201599,
  80,
  'DeAndre Jordan',
  1610612746,
  'LAC',
  82,
  2820,
  379,
  534,
  0.71,
  1,
  4,
  0.25,
  187,
  471,
  0.397,
  397,
  829,
  1226,
  61,
  81,
  183,
  109,
  245,
  946,
  1949,
  0.56,
  0.74],
 [202702,
  80,
  'Kenneth Faried',
  1610612743,
  'DEN',
  75,
  2086,
  373,
  736,
  0.507,
  1,
  8,
  0.125,
  199,
  288,
  0.691,
  242,
  426,
  668,
  89,
  62,
  57,
  118,
  211,
  946,
  1252,
  0.75,
  0.53],
 [203496,
  83,
  'Robert Covington',
  1610612755,
  'PHI',
  70,
  1956,
  299,
  756,
  0.396,
  167,
  446,
  0.374,
  178,
  217,
  0.82,
  65,
  251,
  316,
  105,
  97,
  31,
  128,
  189,
  943,
  868,
  0.82,
  0.76],
 [101139,
  84,
  'CJ Miles',
  1610612754,
  'IND',
  70,
  1841,
  329,
  827,
  0.398,
  154,
  446,
  0.345,
  130,
  161,
  0.807,
  18,
  196,
  214,
  75,
  60,
  26,
  73,
  132,
  942,
  715,
  1.03,
  0.82],
 [203079,
  85,
  'Dion Waiters',
  1610612760,
  'OKC',
  80,
  2208,
  375,
  946,
  0.396,
  73,
  246,
  0.297,
  117,
  172,
  0.68,
  41,
  151,
  192,
  163,
  90,
  21,
  113,
  155,
  940,
  667,
  1.44,
  0.8],
 [2547,
  86,
  'Chris Bosh',
  1610612748,
  'MIA',
  44,
  1556,
  343,
  745,
  0.46,
  63,
  168,
  0.375,
  179,
  232,
  0.772,
  46,
  264,
  310,
  95,
  41,
  25,
  95,
  69,
  928,
  849,
  1.0,
  0.43],
 [203110,
  87,
  'Draymond Green',
  1610612744,
  'GSW',
  79,
  2490,
  339,
  765,
  0.443,
  111,
  329,
  0.337,
  132,
  200,
  0.66,
  114,
  533,
  647,
  291,
  123,
  99,
  133,
  253,
  921,
  1454,
  2.19,
  0.93],
 [201147,
  88,
  'Corey Brewer',
  1610612745,
  'HOU',
  80,
  2087,
  343,
  805,
  0.426,
  63,
  235,
  0.268,
  168,
  226,
  0.743,
  80,
  217,
  297,
  173,
  114,
  19,
  131,
  173,
  917,
  869,
  1.32,
  0.87],
 [201586,
  88,
  'Serge Ibaka',
  1610612760,
  'OKC',
  64,
  2116,
  374,
  786,
  0.476,
  77,
  205,
  0.376,
  92,
  110,
  0.836,
  135,
  364,
  499,
  55,
  30,
  155,
  97,
  194,
  917,
  1129,
  0.57,
  0.31],

In [ ]:
pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,1629029,1,Luka Dončić,1610612742,DAL,22,899,225,504,0.446,68,211,0.322,117,153,0.765,16,192,208,178,41,8,90,56,635,665,1.98,0.46
1,202681,2,Kyrie Irving,1610612742,DAL,22,879,186,398,0.467,53,136,0.390,62,73,0.849,22,59,81,113,23,7,51,62,487,437,2.22,0.45
2,1628369,3,Jayson Tatum,1610612738,BOS,19,768,159,372,0.427,39,138,0.283,118,137,0.861,17,167,184,119,20,13,50,54,475,529,2.38,0.40
3,1627759,4,Jaylen Brown,1610612738,BOS,19,707,175,339,0.516,36,110,0.327,68,103,0.660,22,91,113,62,23,12,51,51,454,414,1.22,0.45
4,1630162,5,Anthony Edwards,1610612750,MIN,16,649,156,324,0.481,46,115,0.400,83,102,0.814,18,94,112,104,24,9,52,37,441,451,2.00,0.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,1641765,198,Olivier-Maxence Prosper,1610612742,DAL,3,9,0,2,0.000,0,0,0.000,0,0,0.000,0,3,3,1,0,0,0,0,0,2,0.00,0.00
210,1631115,198,Orlando Robinson,1610612748,MIA,1,2,0,1,0.000,0,1,0.000,0,0,0.000,0,1,1,1,0,0,0,0,0,1,0.00,0.00
211,203933,198,T.J. Warren,1610612750,MIN,3,11,0,2,0.000,0,1,0.000,0,0,0.000,2,1,3,1,0,0,0,0,0,2,0.00,0.00
212,201152,198,Thaddeus Young,1610612756,PHX,1,4,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
213,203648,198,Thanasis Antetokounmpo,1610612749,MIL,2,5,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,1,1,0,1,0,2,0.00,0.00

In [ ]:
temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)
temp_df2 = pd.DataFrame({'Year':['2014-15' for i in range(len(temp_df1))], 
                         'Season_type':['Regular%20Season' for i in range(len(temp_df1))]
                         })
temp_df3 = pd.concat([temp_df2, temp_df1], axis = 1)

In [ ]:
del temp_df1, temp_df2, temp_df3

In [ ]:
df_cols = ['Year', 'Season_type'] + table_headers

In [ ]:
pd.DataFrame(columns = df_cols)

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS, EFF, AST_TOV, STL_TOV]
Index: []

In [ ]:
headers = {
    'accept': '*/*',
'accept-encoding':
'gzip, deflate, br, zstd',
'accept-language':
'en-US,en;q=0.9',
'connection':
'keep-alive',
'host':
'stats.nba.com',
'origin':
'https://www.nba.com',
'referer':
'https://www.nba.com/', 
'sec-ch-ua':
'"Not A(Brand";v="8", "Chromium";v="132", "Google Chrome";v="132"',
'sec-ch-ua-mobile':
'?0',
'sec-ch-ua-platform':
'"Windows"',
'sec-fetch-dest':
'empty',
'sec-fetch-mode':
'cors',
'sec-fetch-site':
'same-site',
'user-agent':
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36'
}

In [ ]:
df = pd.DataFrame(columns = df_cols)
season_types = ['Regular%20Season', 'Playoffs']
years = ['2014-15', "2015-16", "2016-17","2017-18","2018-19","2019-20","2020-21","2021-22", "2022-23", "2023-24"]

begin_loop = time.time()

for y in years:
    for s in season_types:
        api_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season='+y+'&SeasonType='+s+'&StatCategory=PTS'
        r = requests.get(url=api_url).json()
        temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)
        temp_df2 = pd.DataFrame({'Year':[y for i in range(len(temp_df1))], 
                                'Season_type':[s for i in range(len(temp_df1))]})
        temp_df3 = pd.concat([temp_df2, temp_df1], axis = 1)
        df = pd.concat([df, temp_df3], axis = 0)
        print(f'Finished scraping data for the {y} {s}. ')
        lag = np.random.uniform(low = 5, high = 20)
        print(f'...waiting {round(lag,1)}seconds')
        time.sleep(lag)


print(f'Process Completed. Total run time: {round((time.time()-begin_loop)/60,2)}')
df.to_excel('nba_player_data.xlsx', index = False)

C:\Users\ryanc\AppData\Local\Temp\ipykernel_16628\2891115205.py:15: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Finished scraping data for the 2014-15 Regular%20Season.
...waiting 12.3seconds
Finished scraping data for the 2014-15 Playoffs.
...waiting 11.1seconds
Finished scraping data for the 2015-16 Regular%20Season.
...waiting 18.9seconds
Finished scraping data for the 2015-16 Playoffs.
...waiting 14.2seconds
Finished scraping data for the 2016-17 Regular%20Season.
...waiting 18.7seconds
Finished scraping data for the 2016-17 Playoffs.
...waiting 8.2seconds
Finished scraping data for the 2017-18 Regular%20Season.
...waiting 9.7seconds
Finished scraping data for the 2017-18 Playoffs.
...waiting 15.1seconds
Finished scraping data for the 2018-19 Regular%20Season.
...waiting 7.1seconds
Finished scraping data for the 2018-19 Playoffs.
...waiting 17.2seconds
Finished scraping data for the 2019-20 Regular%20Season.
...waiting 19.1seconds
Finished scraping data for the 2019-20 Playoffs.
...waiting 15.2seconds
Finished scraping data for the 2020-21 Regular%20Season.
...waiting 14.7seconds
Finished scraping data for the 2020-21 Playoffs.
...waiting 8.9seconds
Finished scraping data for the 2021-22 Regular%20Season.
...waiting 8.4seconds
Finished scraping data for the 2021-22 Playoffs.
...waiting 5.1seconds
Finished scraping data for the 2022-23 Regular%20Season.
...waiting 8.2seconds
Finished scraping data for the 2022-23 Playoffs.
...waiting 10.8seconds
Finished scraping data for the 2023-24 Regular%20Season.
...waiting 7.0seconds
Finished scraping data for the 2023-24 Playoffs.
...waiting 19.2seconds
Process Completed. Total run time: 4.34

In [ ]:
df

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2014-15,Regular%20Season,201935,1,James Harden,1610612745,HOU,81,2981,647,1470,0.440,208,555,0.375,715,824,0.868,75,384,459,565,154,60,321,208,2217,2202,1.76,0.48
1,2014-15,Regular%20Season,201939,2,Stephen Curry,1610612744,GSW,80,2613,653,1341,0.487,286,646,0.443,308,337,0.914,56,285,341,619,163,16,249,158,1900,2073,2.49,0.66
2,2014-15,Regular%20Season,201566,3,Russell Westbrook,1610612760,OKC,67,2302,627,1471,0.426,86,288,0.299,546,654,0.835,124,364,488,574,140,14,293,184,1886,1857,1.96,0.48
3,2014-15,Regular%20Season,2544,4,LeBron James,1610612739,CLE,69,2493,624,1279,0.488,120,339,0.354,375,528,0.710,51,365,416,511,109,49,272,135,1743,1748,1.88,0.40
4,2014-15,Regular%20Season,203081,5,Damian Lillard,1610612757,POR,82,2925,590,1360,0.434,196,572,0.343,344,398,0.864,49,329,378,507,97,21,222,164,1720,1677,2.28,0.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,2023-24,Playoffs,1641765,198,Olivier-Maxence Prosper,1610612742,DAL,3,9,0,2,0.000,0,0,0.000,0,0,0.000,0,3,3,1,0,0,0,0,0,2,0.00,0.00
210,2023-24,Playoffs,1631115,198,Orlando Robinson,1610612748,MIA,1,2,0,1,0.000,0,1,0.000,0,0,0.000,0,1,1,1,0,0,0,0,0,1,0.00,0.00
211,2023-24,Playoffs,203933,198,T.J. Warren,1610612750,MIN,3,11,0,2,0.000,0,1,0.000,0,0,0.000,2,1,3,1,0,0,0,0,0,2,0.00,0.00
212,2023-24,Playoffs,201152,198,Thaddeus Young,1610612756,PHX,1,4,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
213,2023-24,Playoffs,203648,198,Thanasis Antetokounmpo,1610612749,MIL,2,5,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,1,1,0,1,0,2,0.00,0.00

In [ ]:
data.sample(10)

,Year,Season_type,PLAYER_ID,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,AST_TOV,STL_TOV,season_start_year
342,2014-15,RS,203488,Mike Muscala,1610612737,ATL,40,502,83,151,0.550,9,22,0.409,22,25,0.880,52,67,119,25,16,19,21,52,197,1.19,0.76,2014
1393,2016-17,RS,202738,Isaiah Thomas,1610612738,BOS,76,2569,682,1473,0.463,245,646,0.379,590,649,0.909,42,162,204,448,70,13,210,167,2199,2.13,0.33,2016
905,2015-16,RS,2755,Kevin Martin,1610612759,SAS,55,1095,156,419,0.372,49,136,0.360,153,172,0.890,14,96,110,58,26,3,54,83,514,1.07,0.48,2015
1081,2015-16,RS,2365,Chris Andersen,1610612763,MEM,27,403,38,72,0.528,4,14,0.286,25,36,0.694,36,62,98,12,15,13,9,29,105,1.33,1.67,2015
474,2014-15,RS,203512,Lucas Nogueira,1610612761,TOR,6,23,2,8,0.250,0,0,0.000,2,4,0.500,2,9,11,1,2,0,2,6,6,0.50,1.00,2014
1734,2016-17,RS,2449,Luis Scola,1610612751,BKN,36,461,71,151,0.470,17,50,0.340,25,37,0.676,51,88,139,37,14,4,34,63,184,1.09,0.41,2016
763,2015-16,RS,202355,Hassan Whiteside,1610612748,MIA,73,2125,413,682,0.606,0,0,0.000,214,329,0.650,238,627,865,29,44,269,137,201,1040,0.21,0.32,2015
1044,2015-16,RS,1897,Metta World Peace,1610612747,LAL,35,590,55,177,0.311,26,84,0.310,40,57,0.702,19,70,89,27,22,11,15,67,176,1.80,1.47,2015
457,2014-15,RS,2030,Kenyon Martin,1610612749,MIL,11,104,9,22,0.409,0,0,0.000,2,2,1.000,6,13,19,5,5,6,3,13,20,1.67,1.67,2014
1060,2015-16,RS,2760,Anderson Varejao,1610612744,GSW,53,496,53,124,0.427,0,1,0.000,32,50,0.640,37,104,141,35,16,10,22,70,138,1.59,0.73,2015

In [ ]:
data.shape

(7473, 30)

In [ ]:
data.isna().sum()

Year           0
Season_type    0
PLAYER_ID      0
RANK           0
PLAYER         0
TEAM_ID        0
TEAM           0
GP             0
MIN            0
FGM            0
FGA            0
FG_PCT         0
FG3M           0
FG3A           0
FG3_PCT        0
FTM            0
FTA            0
FT_PCT         0
OREB           0
DREB           0
REB            0
AST            0
STL            0
BLK            0
TOV            0
PF             0
PTS            0
EFF            0
AST_TOV        0
STL_TOV        0
dtype: int64

In [ ]:
data['season_start_year'] = data["Year"].str[:4].astype(int)

In [ ]:
data.TEAM.nunique()

30

In [ ]:
data['Season_type'].replace('Regular%20Season','RS', inplace = True)

C:\Users\ryanc\AppData\Local\Temp\ipykernel_16628\641725032.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [ ]:
rs_df = data[data['Season_type']=='RS']
playoffs_df = data[data['Season_type']=='Playoffs']

In [ ]:
rs_df

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS, EFF, AST_TOV, STL_TOV, season_start_year]
Index: []

In [ ]:
data.columns

Index(['Year', 'Season_type', 'PLAYER_ID', 'PLAYER', 'TEAM_ID', 'TEAM', 'GP',
       'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
       'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS', 'AST_TOV', 'STL_TOV', 'season_start_year'],
      dtype='object')

In [ ]:
total_cols = ['MIN', 'FGM', 'FGA', 'FG3M','FG3A','FTM', 'FTA',
              'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PTS']

In [ ]:
data.corr

<bound method DataFrame.corr of          Year       Season_type  PLAYER_ID  RANK                   PLAYER  \
0     2014-15  Regular%20Season     201935     1             James Harden
1     2014-15  Regular%20Season     201939     2            Stephen Curry
2     2014-15  Regular%20Season     201566     3        Russell Westbrook
3     2014-15  Regular%20Season       2544     4             LeBron James
4     2014-15  Regular%20Season     203081     5           Damian Lillard
...       ...               ...        ...   ...                      ...
7468  2023-24          Playoffs    1641765   198  Olivier-Maxence Prosper
7469  2023-24          Playoffs    1631115   198         Orlando Robinson
7470  2023-24          Playoffs     203933   198              T.J. Warren
7471  2023-24          Playoffs     201152   198           Thaddeus Young
7472  2023-24          Playoffs     203648   198   Thanasis Antetokounmpo

         TEAM_ID TEAM  GP   MIN  FGM   FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  \
0     1610612745  HOU  81  2981  647  1470   0.440   208   555    0.375  715
1     1610612744  GSW  80  2613  653  1341   0.487   286   646    0.443  308
2     1610612760  OKC  67  2302  627  1471   0.426    86   288    0.299  546
3     1610612739  CLE  69  2493  624  1279   0.488   120   339    0.354  375
4     1610612757  POR  82  2925  590  1360   0.434   196   572    0.343  344
...          ...  ...  ..   ...  ...   ...     ...   ...   ...      ...  ...
7468  1610612742  DAL   3     9    0     2   0.000     0     0    0.000    0
7469  1610612748  MIA   1     2    0     1   0.000     0     1    0.000    0
7470  1610612750  MIN   3    11    0     2   0.000     0     1    0.000    0
7471  1610612756  PHX   1     4    0     0   0.000     0     0    0.000    0
7472  1610612749  MIL   2     5    0     0   0.000     0     0    0.000    0

      FTA  FT_PCT  OREB  DREB  REB  AST  STL  BLK  TOV   PF   PTS   EFF  \
0     824   0.868    75   384  459  565  154   60  321  208  2217  2202
1     337   0.914    56   285  341  619  163   16  249  158  1900  2073
2     654   0.835   124   364  488  574  140   14  293  184  1886  1857
3     528   0.710    51   365  416  511  109   49  272  135  1743  1748
4     398   0.864    49   329  378  507   97   21  222  164  1720  1677
...   ...     ...   ...   ...  ...  ...  ...  ...  ...  ...   ...   ...
7468    0   0.000     0     3    3    1    0    0    0    0     0     2
7469    0   0.000     0     1    1    1    0    0    0    0     0     1
7470    0   0.000     2     1    3    1    0    0    0    0     0     2
7471    0   0.000     0     0    0    0    0    0    0    0     0     0
7472    0   0.000     0     0    0    0    1    1    0    1     0     2

      AST_TOV  STL_TOV  season_start_year
0        1.76     0.48               2014
1        2.49     0.66               2014
2        1.96     0.48               2014
3        1.88     0.40               2014
4        2.28     0.44               2014
...       ...      ...                ...
7468     0.00     0.00               2023
7469     0.00     0.00               2023
7470     0.00     0.00               2023
7471     0.00     0.00               2023
7472     0.00     0.00               2023

[7473 rows x 31 columns]>

In [ ]:
data_per_min = data.groupby(['PLAYER','PLAYER_ID', 'Year'])[total_cols].sum().reset_index()
for col in data_per_min.columns[4:]:
    data_per_min[col] = data_per_min[col]/data_per_min['MIN']

data_per_min['FG%'] = data_per_min['FGM']/data_per_min['FGA']
data_per_min['3PT%'] = data_per_min['FG3M']/data_per_min['FG3A']
data_per_min['FT%'] = data_per_min['FTM']/data_per_min['FTA']
data_per_min['FG3A%'] = data_per_min['FG3A']/data_per_min['FGA']
data_per_min['PTS/FGA'] = data_per_min['PTS']/data_per_min['FGA']
data_per_min['FG3M/FGM'] = data_per_min['FG3M']/data_per_min['FGM']
data_per_min['FTA/FGA'] = data_per_min['FTA']/data_per_min['FGA']
data_per_min['TRU%'] = 0.5 *data_per_min['PTS']/(data_per_min['FGA'] + 0.475*data_per_min['FTA'])
data_per_min['AST_TOV'] = data_per_min['AST']/data_per_min['TOV']

data_per_min = data_per_min[data_per_min['MIN']>=50]
data_per_min.drop(columns='PLAYER_ID', inplace=True)
data_per_min.drop(columns='Year', inplace=True)
data_per_min.drop(columns='PLAYER', inplace=True)
data_per_min.corr()

,MIN,FGM,FGA,FG3M,FG3A,FTM,FTA,OREB,DREB,REB,AST,STL,BLK,TOV,PTS,FG%,3PT%,FT%,FG3A%,PTS/FGA,FG3M/FGM,FTA/FGA,TRU%,AST_TOV
MIN,1.000000,0.434262,0.344467,0.196970,0.124186,0.326305,0.249084,-0.101096,0.050891,-0.010842,0.237062,0.090532,-0.040766,0.110179,0.465826,0.211826,0.187552,0.229471,0.019129,0.292577,0.035660,0.015056,0.364589,0.130019
FGM,0.434262,1.000000,0.879278,0.134332,0.079982,0.582981,0.526484,0.086610,0.187787,0.158703,0.185165,-0.042291,0.084902,0.360349,0.949893,0.364027,0.097128,0.222724,-0.231526,0.308994,-0.215423,0.010317,0.385263,-0.067054
FGA,0.344467,0.879278,1.000000,0.370621,0.384042,0.547784,0.439264,-0.190529,-0.044125,-0.110860,0.311554,0.028968,-0.156997,0.407216,0.901556,-0.098979,0.200900,0.337410,0.053217,-0.057682,0.045555,-0.159815,0.022097,0.075069
FG3M,0.196970,0.134332,0.370621,1.000000,0.960582,-0.026966,-0.182427,-0.651236,-0.470576,-0.585400,0.177137,0.039337,-0.481282,-0.036606,0.309540,-0.414808,0.627301,0.394398,0.867399,-0.112072,0.888590,-0.429960,0.113531,0.268890
FG3A,0.124186,0.079982,0.384042,0.960582,1.000000,-0.037119,-0.193593,-0.684601,-0.502404,-0.620376,0.200216,0.080345,-0.512367,-0.004044,0.257644,-0.540850,0.530918,0.394369,0.906853,-0.247803,0.877382,-0.449622,-0.051852,0.286397
FTM,0.326305,0.582981,0.547784,-0.026966,-0.037119,1.000000,0.939494,0.099452,0.166437,0.150468,0.227292,0.084875,0.085366,0.408546,0.738033,0.152788,0.010832,0.276101,-0.257429,0.486819,-0.256368,0.609113,0.272958,-0.070984
FTA,0.249084,0.526484,0.439264,-0.182427,-0.193593,0.939494,1.000000,0.278328,0.295300,0.311008,0.131574,0.085345,0.228641,0.394412,0.643332,0.250051,-0.101557,-0.008971,-0.391359,0.521210,-0.382702,0.763637,0.229574,-0.176223
OREB,-0.101096,0.086610,-0.190529,-0.651236,-0.684601,0.099452,0.278328,1.000000,0.709533,0.890475,-0.427944,-0.166786,0.638102,-0.053579,-0.047492,0.554492,-0.521371,-0.419064,-0.699492,0.339253,-0.663175,0.451575,0.164207,-0.513713
DREB,0.050891,0.187787,-0.044125,-0.470576,-0.502404,0.166437,0.295300,0.709533,1.000000,0.952470,-0.307868,-0.136615,0.584856,0.041505,0.087709,0.473196,-0.370679,-0.304021,-0.529800,0.316430,-0.500149,0.347081,0.192619,-0.419128
REB,-0.010842,0.158703,-0.110860,-0.585400,-0.620376,0.150468,0.311008,0.890475,0.952470,1.000000,-0.383803,-0.160320,0.653517,0.003639,0.036106,0.545269,-0.461269,-0.377420,-0.644504,0.350991,-0.609658,0.419341,0.195369,-0.490860
AST,0.237062,0.185165,0.311554,0.177137,0.200216,0.227292,0.131574,-0.427944,-0.307868,-0.383803,1.000000,0.345844,-0.360602,0.613929,0.246705,-0.214388,0.143985,0.232422,0.110914,-0.129265,0.084402,-0.097304,-0.107915,0.681012
STL,0.090532,-0.042291,0.028968,0.039337,0.080345,0.084875,0.085345,-0.166786,-0.136615,-0.160320,0.345844,1.000000,-0.123634,0.233204,0.004082,-0.153105,0.028761,-0.029046,0.077783,-0.092370,0.043746,0.029820,-0.129540,0.239192
BLK,-0.040766,0.084902,-0.156997,-0.481282,-0.512367,0.085366,0.228641,0.638102,0.584856,0.653517,-0.360602,-0.123634,1.000000,-0.051134,-0.015963,0.488562,-0.402240,-0.333687,-0.518633,0.333055,-0.487046,0.363046,0.202976,-0.413642
TOV,0.110179,0.360349,0.407216,-0.036606,-0.004044,0.408546,0.394412,-0.053579,0.041505,0.003639,0.613929,0.233204,-0.051134,1.000000,0.386008,-0.010617,-0.055656,0.043253,-0.163476,0.016435,-0.184734,0.129663,-0.054955,-0.044277
PTS,0.465826,0.949893,0.901556,0.309540,0.257644,0.738033,0.643332,-0.047492,0.087709,0.036106,0.246705,0.004082,-0.015963,0.386008,1.000000,0.225591,0.207861,0.337072,-0.061651,0.356197,-0.044804,0.104758,0.394671,-0.012773
FG%,0.211826,0.364027,-0.098979,-0.414808,-0.540850,0.152788,0.250051,0.554492,0.473196,0.545269,-0.214388,-0.153105,0.488562,-0.010617,0.225591,1.000000,-0.200155,-0.196647,-0.595650,0.805005,-0.545870,0.362349,0.794944,-0.300145
3PT%,0.187552,0.097128,0.200900,0.627301,0.530918,0.010832,-0.101557,-0.521371,-0.370679,-0.461269,0.143985,0.028761,-0.402240,-0.055656,0.207861,-0.200155,1.000000,0.309081,0.520211,0.041058,0.574053,-0.289884,0.211756,0.212119
FT%,0.229471,0.222724,0.337410,0.394398,0.394369,0.276101,-0.008971,-0.419064,-0.304021,-0.377420,0.232422,-0.029046,-0.333687,0.043253,0.337072,-0.196647,0.309081,1.000000,0.315584,0.041304,0.302270,-0.243177,0.193638,0.266349
FG3A%,0.019129,-0.231526,0.053217,0.867399,0.906853,-0.257429,-0.391359,-0.699492,-0.529800,-0.644504,0.110914,0.077783,-0.518633,-0.163476,-0.061651,-0.595650,0.520211,0.315584,1.000000,-0.306273,0.970725,-0.496351,-0.097587,0.309469
PTS/FGA,0.292577,0.308994,-0.057682,-0.112072,-0.247803,0.486819,0.521210,0.339253,0.316430,0.350991,-0.129265,-0.092370,0.333055,0.016435,0.356197,0.805005,0.041058,0.041304,-0.306273,1.000000,-0.247744,0.630660,0.898494,-0.226805
FG3M/FGM,0.035660,-0.215423,0.045555,0.888590,0.877382,-0.256368,-0.382702,-0.663175,-0.500149,-0.609658,0.084402,0.043746,-0.487046,-0.184734,-0.044804,-0.545870,0.574053,0.302270,0.970725,-0.247744,1.000000,-0.479782,-0.031714,0.291721
FTA/FGA,0.015056,0.010317,-0.159815,-0.429960,-0.449622,0.609113,0.763637,0.451575,0.347081,0.419341,-0.097304,0.029820,0.363046,0.129663,0.104758,0.362349,-0.289884,-0.243177,-0.496351,0.630660,-0.479782,1.000000,0.231807,-0.271447
TRU%,0.364589,0.385263,0.022097,0.113531,-0.051852,0.272958,0.229574,0.164207,0.192619,0.195369,-0.107915,-0.129540,0.202976,-0.054955,0.394671,0.794944,0.211756,0.193638,-0.097587,0.898494,-0.031714,0.231807,1.000000,-0.130006
AST_TOV,0.130019,-0.067054,0.075069,0.268890,0.286397,-0.070984,-0.176223,-0.513713,-0.419128,-0.490860,0.681012,0.239192,-0.413642,-0.044277,-0.012773,-0.300145,0.212119,0.266349,0.309469,-0.226805,0.291721,-0.271447,-0.130006,1.000000

In [ ]:
fig = px.histogram(x=playoffs_df['MIN'], histnorm = 'percent')
fig.show()

In [ ]:
def hist_data(df=rs_df, min_MIN=0, min_GP=0):
    return df.loc[(df['MIN']>=min_MIN) & (df['GP']>=min_GP), 'MIN']/\
    df.loc[(df['MIN']>=min_MIN) & (df['GP']>=min_GP), 'GP']

In [ ]:
fig = go.Figure()
fig.add_trace(go.Histogram(x=hist_data(rs_df,50,5), histnorm='percent', name='RS',
                           xbins={'start':0,'end':46,'size':1}))
fig.add_trace(go.Histogram(x=hist_data(playoffs_df,5,1), histnorm='percent',
                           name='Playoffs', xbins={'start':0,'end':46,'size':1}))
fig.update_layout(barmode='overlay')
fig.update_traces(opacity=0.5)
fig.show()

In [ ]:
change_df = data.groupby('season_start_year')[total_cols].sum().reset_index()
change_df['POSS_est'] = change_df['FGA']-change_df['OREB']+change_df['TOV']+0.44*change_df['FTA']
change_df = change_df[list(change_df.columns[0:2])+['POSS_est']+list(change_df.columns[2:-1])]

change_df['FG%'] = change_df['FGM']/change_df['FGA']
change_df['3PT%'] = change_df['FG3M']/change_df['FG3A']
change_df['FT%'] = change_df['FTM']/change_df['FTA']
change_df['AST%'] = change_df['AST']/change_df['FGM']
change_df['FG3A%'] = change_df['FG3A']/change_df['FGA']
change_df['PTS/FGA'] = change_df['PTS']/change_df['FGA']
change_df['FG3M/FGM'] = change_df['FG3M']/change_df['FGM']
change_df['FTA/FGA'] = change_df['FTA']/change_df['FGA']
change_df['TRU%'] = 0.5*change_df['PTS']/(change_df['FGA']+0.475*change_df['FTA'])
change_df['AST_TOV'] = change_df['AST']/change_df['TOV']

change_df

,season_start_year,MIN,POSS_est,FGM,FGA,FG3M,FG3A,FTM,FTA,OREB,DREB,REB,AST,STL,BLK,TOV,PTS,FG%,3PT%,FT%,AST%,FG3A%,PTS/FGA,FG3M/FGM,FTA/FGA,TRU%,AST_TOV
0,2014,634546,253004.12,98251,219265,20724,59276,45098,60248,28566,85231,113797,57727,20261,12665,35796,262324,0.448092,0.349619,0.748539,0.587546,0.270340,1.196379,0.210929,0.274773,0.529129,1.612666
1,2015,636391,258064.80,100351,222344,22524,63673,46516,61520,27426,87611,115037,58251,20562,13046,36078,269742,0.451332,0.353745,0.756112,0.580473,0.286372,1.213174,0.224452,0.276688,0.536126,1.614585
2,2016,632482,258443.80,102147,223333,25408,71018,46806,60620,26470,87173,113643,59162,20143,12409,34908,276508,0.457375,0.357768,0.772121,0.579185,0.317992,1.238097,0.248740,0.271433,0.548350,1.694798
3,2017,633425,260904.52,103729,225523,27530,76245,43721,57008,25397,88678,114075,60739,20181,12636,35695,278709,0.459949,0.361073,0.766927,0.585555,0.338081,1.235834,0.265403,0.252781,0.551677,1.701611
4,2018,634231,268739.84,107374,233717,29817,84143,46671,60811,27128,91360,118488,64257,19940,12984,35394,291236,0.459419,0.354361,0.767476,0.598441,0.360021,1.246105,0.277693,0.260191,0.554519,1.815477
5,2019,552262,234384.64,92997,202223,28032,78279,40949,52906,22802,79318,102120,55445,17368,11085,31685,254975,0.459874,0.358104,0.773995,0.596202,0.387092,1.260861,0.301429,0.261622,0.560746,1.749882
6,2020,562518,235759.48,95849,205754,29549,80653,39624,50917,22918,80151,103069,57311,17491,11272,30520,260871,0.465843,0.366372,0.778208,0.597930,0.391988,1.267878,0.308287,0.247465,0.567260,1.877818
7,2021,635572,264004.96,106569,231293,32733,92552,44740,57709,27052,89602,116654,64618,20006,12387,34372,290611,0.460753,0.353671,0.775269,0.606349,0.400150,1.256463,0.307153,0.249506,0.561665,1.879960
8,2022,635386,266600.04,110010,231870,32382,89926,48136,61516,27403,86695,114098,66265,19078,12250,35066,300538,0.474447,0.360096,0.782496,0.602354,0.387829,1.296149,0.294355,0.265304,0.575545,1.889722
9,2023,633272,263500.48,110138,232542,33501,91831,44504,56767,27618,86355,113973,69408,19438,13434,33599,298281,0.473626,0.364811,0.783977,0.630191,0.394901,1.282697,0.304173,0.244115,0.574709,2.065776

In [ ]:
change_per48_df = change_df.copy()
for col in change_per48_df.columns[2:18]:
    change_per48_df[col] = (change_per48_df[col]/change_per48_df['MIN'])*48*5

change_per48_df.drop(columns='MIN', inplace=True)

fig = go.Figure()
for col in change_per48_df.columns[1:]:
    fig.add_trace(go.Scatter(x=change_per48_df['season_start_year'],
                             y=change_per48_df[col], name=col))
fig.show()

In [ ]:
change_df_per48_df.columns[2:18]

Index(['FGM', 'FGA', 'FG3M', 'FG3A', 'FTM', 'FTA', 'OREB', 'DREB', 'REB',
       'AST', 'STL', 'BLK', 'TOV', 'PTS', 'FG%', '3PT%'],
      dtype='object')

In [ ]:
rs_change_df = rs_df.groupby('season_start_year')[total_cols].sum().reset_index()
playoffs_change_df = playoffs_df.groupby('season_start_year')[total_cols].sum().reset_index()

for i in [rs_change_df,playoffs_change_df]:
    i['POSS_est'] = i['FGA']-i['OREB']+i['TOV']+0.44*i['FTA']
    i['POSS_per_48'] = (i['POSS_est']/i['MIN'])*48*5
    
    i['FG%'] = i['FGM']/i['FGA']
    i['3PT%'] = i['FG3M']/i['FG3A']
    i['FT%'] = i['FTM']/i['FTA']
    i['AST%'] = i['AST']/i['FGM']
    i['FG3A%'] = i['FG3A']/i['FGA']
    i['PTS/FGA'] = i['PTS']/i['FGA']
    i['FG3M/FGM'] = i['FG3M']/i['FGM']
    i['FTA/FGA'] = i['FTA']/i['FGA']
    i['TRU%'] = 0.5*i['PTS']/(i['FGA']+0.475*i['FTA'])
    i['AST_TOV'] = i['AST']/i['TOV']
    for col in total_cols:
        i[col] = 100*i[col]/i['POSS_est']
    i.drop(columns=['MIN','POSS_est'], inplace=True)
    
rs_change_df

Empty DataFrame
Columns: [season_start_year, FGM, FGA, FG3M, FG3A, FTM, FTA, OREB, DREB, REB, AST, STL, BLK, TOV, PTS, POSS_per_48, FG%, 3PT%, FT%, AST%, FG3A%, PTS/FGA, FG3M/FGM, FTA/FGA, TRU%, AST_TOV]
Index: []

In [ ]:
rs_df

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS, EFF, AST_TOV, STL_TOV, season_start_year]
Index: []